#!/bin/bash
# DocBrain Azure resource bootstrap.
# Creates core Azure resources and writes a local env template instead of echoing secrets to stdout.
#
# Prerequisites:
#   - Azure CLI installed
#   - Logged in with `az login`
#
# Usage:
#   ./scripts/setup_azure.sh

set -euo pipefail

RESOURCE_GROUP="${RESOURCE_GROUP:-rg-docbrain}"
LOCATION="${LOCATION:-eastus2}"
SEARCH_SERVICE="${SEARCH_SERVICE:-docbrain-search}"
STORAGE_ACCOUNT="${STORAGE_ACCOUNT:-docbrainstorage2026}"
OUTPUT_ENV_FILE="${OUTPUT_ENV_FILE:-.env.generated}"

echo "== DocBrain Azure Setup =="
echo "Resource Group: $RESOURCE_GROUP"
echo "Location:       $LOCATION"
echo "Output file:    $OUTPUT_ENV_FILE"
echo

echo "[1/3] Creating resource group..."
az group create \
  --name "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --output none

echo "[2/3] Creating Azure AI Search service..."
az search service create \
  --name "$SEARCH_SERVICE" \
  --resource-group "$RESOURCE_GROUP" \
  --sku free \
  --location "$LOCATION" \
  --output none

SEARCH_ENDPOINT="https://${SEARCH_SERVICE}.search.windows.net"
SEARCH_KEY="$(az search admin-key show \
  --service-name "$SEARCH_SERVICE" \
  --resource-group "$RESOURCE_GROUP" \
  --query "primaryKey" \
  --output tsv)"

echo "[3/3] Creating Azure Storage account..."
az storage account create \
  --name "$STORAGE_ACCOUNT" \
  --resource-group "$RESOURCE_GROUP" \
  --sku Standard_LRS \
  --location "$LOCATION" \
  --output none

STORAGE_CONNECTION_STRING="$(az storage account show-connection-string \
  --name "$STORAGE_ACCOUNT" \
  --resource-group "$RESOURCE_GROUP" \
  --query "connectionString" \
  --output tsv)"

cat > "$OUTPUT_ENV_FILE" <<EOF
# Generated by scripts/setup_azure.sh
AZURE_SEARCH_ENDPOINT=$SEARCH_ENDPOINT
AZURE_SEARCH_KEY=$SEARCH_KEY
AZURE_SEARCH_INDEX=docbrain-articles
AZURE_STORAGE_CONNECTION_STRING=$STORAGE_CONNECTION_STRING
AZURE_STORAGE_CONTAINER=docbrain-uploads
EOF

echo
echo "Resource setup complete."
echo "The generated settings were written to $OUTPUT_ENV_FILE."
echo "Next steps:"
echo "1. Review the file locally and merge the values you need into .env."
echo "2. Create your Azure AI Foundry project and model deployments."
echo "3. Add Foundry and Azure OpenAI settings to .env or GitHub secrets."
